### ISSUE TITLE
Error quan no hi ha els fitxer de properties o de systemproperties

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#54]
Es produeix un NullPointer quan no hi ha els fitxer de properties o de systemproperties. S'hauria de controlar l'error i actualitzar el codi generat de genapp2

jboss.persistenceunit."demogenapp.ear#demogenappPU": java.lang.NullPointerException
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:195)
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:125)
	at org.wildfly.security.elytron-private@1.6.6.Final-redhat-00001//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:662)
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:209)
	at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at deployment.demogenapp.ear//org.fundaciobit.demogenapp.commons.utils.Configuracio.getFilesProperties(Configuracio.java:35)
	at deployment.demogenapp.ear//org.fundaciobit.demogenapp.commons.utils.Configuracio.getSystemAndFileProperties(Configuracio.java:55)
	at deployment.demogenapp.ear//org.fundaciobit.demogenapp.hibernate.CustomHibernatePersistenceProvider.createContainerEntityManagerFactory(CustomHibernatePersistenceProvider.java:33)
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:357)
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$1300(PersistenceUnitServiceImpl.java:70)
	at org.jboss.as.jpa@7.2.8.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:187)
	... 9 more

**Comment by ptrias-fundaciobit** [comment]
Solucionat al issue 96:

Afegir codi per controlar que s'hagin definit propietats correctament #96
